external-secrets:
  crds:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi

  extraArgs:
    loglevel: debug

  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi

  certController:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
