apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prestashop-elsuenodediana-db
  namespace: prestashop-elsuenodediana-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: mariadb-root-password
      remoteRef:
        key: /prestashop-elsuenodediana-db
        property: mariadb_rootpsswd
    - secretKey: mariadb-password
      remoteRef:
        key: /prestashop-elsuenodediana-db
        property: mariadb_psswd
