# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hass-appdaemon
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: hass-appdaemon
  data:
    - secretKey: TOKEN
      remoteRef:
        key: /home-assistant/appdaemon
        property: token
    - secretKey: LATITUDE
      remoteRef:
        key: /home-assistant/appdaemon
        property: latitude
    - secretKey: LONGITUDE
      remoteRef:
        key: /home-assistant/appdaemon
        property: longitude
    - secretKey: ELEVATION
      remoteRef:
        key: /home-assistant/appdaemon
        property: elevation
