apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: torrenttickarr-secrets
  namespace: torrenttickarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: torrenttickarr-secrets
    template:
      type: Opaque
  data:
    - secretKey: USERNAME
      remoteRef:
        key: /torrenttickarr
        property: USERNAME
    - secretKey: PASSWORD_HDO
      remoteRef:
        key: /torrenttickarr
        property: PASSWORD_HDO
    - secretKey: PASSWORD_TORRENTEROS
      remoteRef:
        key: /torrenttickarr
        property: PASSWORD_TORRENTEROS
    - secretKey: PASSWORD_TORRENTLAND
      remoteRef:
        key: /torrenttickarr
        property: PASSWORD_TORRENTLAND
    - secretKey: PASSWORD_TORRENTLEECH
      remoteRef:
        key: /torrenttickarr
        property: PASSWORD_TORRENTLEECH
    - secretKey: USERNAME_QB
      remoteRef:
        key: /torrenttickarr
        property: USERNAME_QB
    - secretKey: PASSWORD_QB
      remoteRef:
        key: /torrenttickarr
        property: PASSWORD_QB
