apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: KC_DB_USERNAME
      remoteRef:
        key: /keycloak
        property: db_username
    - secretKey: KC_DB_PASSWORD
      remoteRef:
        key: /keycloak
        property: db_password
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: /keycloak
        property: admin_username
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: /keycloak
        property: admin_password

