apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: youtarr-secrets
  namespace: youtarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /youtarr
        property: postgres_password
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /youtarr
        property: postgres_user
    - secretKey: GOOGLE_OAUTH_CLIENT_ID
      remoteRef:
        key: /oauth2-proxy/google
        property: client-id
